# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "./internal/lookoutui"
    schedule:
      interval: "weekly"
    groups:
      lookoutui:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "./website"
    schedule:
      interval: "weekly"
    groups:
      website:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod:
        patterns:
          - "*"
    # Ignore k8s related dependencies since they should be
    # upgraded manually
    ignore:
      - dependency-name: k8s.io/kubectl
      - dependency-name: k8s.io/kubelet
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
      - dependency-name: k8s.io/client-go
      - dependency-name: k8s.io/component-helpers

  - package-ecosystem: "docker"
    directory: "./build"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "./client/python"
    schedule:
      interval: "weekly"
    groups:
      client-python:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "./third_party/airflow"
    schedule:
      interval: "weekly"
    groups:
      third-party-airflow:
        patterns:
          - "*"
