apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "lookout.name" . }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ required "A value is required for .Values.ingressClass" .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: {{ required "A value is required for .Values.clusterIssuer" .Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ required "A value is required for .Values.clusterIssuer" .Values.clusterIssuer }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 -}}
    {{- end }}
  labels:
    {{- include "lookout.labels.all" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 -}}
    {{- end }}
spec:
  rules:
  {{- $root := . -}}
  {{  range required "A value is required for .Values.hostnames" .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "lookout.name" $root }}
            servicePort: {{ $root.Values.applicationConfig.httpPort }}
  {{ end }}
  tls:
    - hosts:
      {{- toYaml .Values.hostnames  | nindent 8 }}
      secretName: lookout-service-tls
