quickstart: true
ingressClass: "nginx"
clusterIssuer: "dummy-value"
hostname: "dummy-value"
replicas: 3

applicationConfig:
  redis:
    masterName: "mymaster"
    addrs:
      - "redis-redis-ha-announce-0.default.svc.cluster.local:26379"
      - "redis-redis-ha-announce-1.default.svc.cluster.local:26379"
      - "redis-redis-ha-announce-2.default.svc.cluster.local:26379"
    poolSize: 1000
  eventsRedis:
    masterName: "mymaster"
    addrs:
      - "redis-redis-ha-announce-0.default.svc.cluster.local:26379"
      - "redis-redis-ha-announce-1.default.svc.cluster.local:26379"
      - "redis-redis-ha-announce-2.default.svc.cluster.local:26379"
    poolSize: 1000

basicAuth:
  users:
    "user1": "password1"

prometheus:
  enabled: true
