redis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  poolSize: 1000

pulsar:
  URL: "pulsar://localhost:6650"
  jobsetEventsTopic: "jobset-events"

paralellism: 1
subscriptionName: "events-ingester"
batchSize: 1048576  #1MB
batchMessages: 10000
batchDuration: 500ms
pulsarReceiveTimeout: 5s
pulsarBackoffTime: 1s
minMessageCompressionSize: 1024