redis:
  addrs:
    - localhost:6379
  password: ""
  db: 1
  poolSize: 1000
pulsar:
  URL: pulsar://pulsar:6650
  jobsetEventsTopic: events
  receiveTimeout: 5s
  backoffTime: 1s
subscriptionName: "events-ingester"
minMessageCompressionSize: 1024
batchSize: 1048576  #1MB
batchDuration: 100ms
batchMessages: 10000
eventRetentionPolicy:
  expiryEnabled: true
  retentionDuration: 336h
