apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "executor.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
data:
  {{ include "executor.application.config.filename" . }}: |
{{- if .Values.applicationConfig }}
{{ toYaml .Values.applicationConfig | indent 4 }}
{{- end }}
