{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "executor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "executor.labels.all" . | indent 4 }}
spec:
  groups:
    - name: armada-pods
      interval: 3s
      rules:
        - record: armada:executor:pod:queue
          expr: |
            sum(kube_pod_labels{label_queue_id!=""}) by (pod, label_queue_id)
            * on (pod) group_left(phase) sum(kube_pod_status_phase==1) by (pod, namespace, phase)

        - record: armada:executor:pod:request:cpu
          expr: |
            sum(
              sum(kube_pod_container_resource_requests_cpu_cores) by (pod)
              * on (pod) group_left(label_queue_id, phase) armada:executor:pod:queue
            ) by (label_queue_id, phase)

        - record: armada:executor:pod:request:memory
          expr: |
            sum(
              sum(kube_pod_container_resource_requests_memory_bytes) by (pod)
              * on (pod) group_left(label_queue_id, phase) armada:executor:pod:queue
            ) by (label_queue_id, phase)

        - record: armada:executor:pod:count
          expr: sum(armada:executor:pod:queue) by (label_queue_id, phase)

        - record: armada:executor:rest:request:histogram95
          expr: histogram_quantile(0.95, sum(rate(rest_client_request_duration_seconds_bucket{service="armada-executor"}[30s])) by (endpoint, verb, url, le))

        - record: armada:executor:log:rate
          expr: sum(rate(log_messages[30s])) by (level)
{{- end }}