image:
  repository: gresearchdev/armada-lookout
  tag: LATEST
resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m
additionalLabels: {}
additionalVolumeMounts: []
additionalVolumes: []
customServiceAccount: null
serviceAccount: null

applicationConfig: {}

extraInitCommand: ""
