httpPort: 8081
grpcPort: 50051
metricsPort: 9000
corsAllowedOrigins:
  - "http://localhost:3000"
  - "http://localhost:8089"
  - "http://localhost:10000"
  - "http://localhost:8081"
auth:
  anonymousAuth: true
  permissionGroupMapping:
    submit_any_jobs: ["everyone"]
    create_queue: ["everyone"]
    delete_queue: ["everyone"]
    cancel_any_jobs: ["everyone"]
    reprioritize_any_jobs: ["everyone"]
    preempt_any_jobs: ["everyone"]
    watch_all_events: ["everyone"]
eventsApiRedis:
  addrs:
    - localhost:6379
  db: 1
postgres:
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: psw
    dbname: lookout
    sslmode: disable
queryapi:
  postgres:
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: psw
      dbname: lookout
      sslmode: disable
pulsar:
  URL: "pulsar://localhost:6650"
redis:
  addrs:
    - localhost:6379
schedulerApiConnection:
  armadaUrl: "localhost:50052"
  forceNoTls: true
