grpcPort: 50051
httpPort: 8080
metricsPort: 9000
corsAllowedOrigins:
  - http://localhost:3000
  - http://localhost:8080
cordon:
  additionalLabels:
    armadaproject.io/cordon-reason: "binoculars"
    armadaproject.io/cordon-user: "<user>"
auth:
  basicAuth:
    enableAuthentication: false
  anonymousAuth: true
impersonateUsers: false
kubernetes:
  QPS: 10000
  Burst: 10000
grpc:
  keepaliveParams:
    maxConnectionIdle: 5m
    time: 2h
    timeout: 20s
  keepaliveEnforcementPolicy:
    minTime: 5m
    permitWithoutStream: false
  tls:
    enabled: false
