postgres:
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: psw
    dbname: scheduler
    sslmode: disable
metrics:
  port: 9003
pulsar:
  URL: "pulsar://localhost:6650"
  jobsetEventsTopic: "events"
  receiveTimeout: 5s
  backoffTime: 1s
  receiverQueueSize: 100
subscriptionName: "scheduler-ingester"
batchSize: 10000
batchDuration: 500ms


