apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "armada-scheduler-pruner.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada-scheduler-pruner.labels.all" . | nindent 4 }}
data:
  {{ include "armada-scheduler-pruner.config.filename" . }}: |
{{- if .Values.pruner.applicationConfig }}
{{ toYaml .Values.pruner.applicationConfig | b64enc | indent 4 }}
{{- end }}
