{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada.labels.all" . | nindent 4 -}}
    {{- if .Values.prometheus.labels }}
    {{- toYaml .Values.prometheus.labels | nindent 4 -}}
    {{- end }}
spec:
  groups:
    - name: armada-server-metrics
      interval: {{ .Values.prometheus.scrapeInterval }}
      rules:
        - record: armada:queue:size
          expr: max(sum(armada_queue_size) by (queueName, pod)) by (queueName) > 0

        - record: armada:queue:priority
          expr: max(sum(armada_queue_priority) by (pool, queueName, pod)) by (pool, queueName)

        - record: armada:queue:ideal_current_share
          expr: >
            (sum(armada:queue:resource:queued{resourceType="cpu"} > bool 0) by (queueName, pool) * (1 / armada:queue:priority))
            / ignoring(queueName) group_left
            sum(sum(armada:queue:resource:queued{resourceType="cpu"} > bool 0) by (queueName, pool) * (1 / armada:queue:priority)) by (pool)
            * 100

        - record: armada:queue:resource:queued
          expr: max(armada_queue_resource_queued) by (pool, queueName, resourceType)

        - record: armada:queue:resource:allocated
          expr: max(armada_queue_resource_allocated) by (pool, cluster, queueName, resourceType, nodeType)

        - record: armada:queue:resource:used
          expr: max(armada_queue_resource_used) by (pool, cluster, queueName, resourceType, nodeType)

        - record: armada:grpc:server:histogram95
          expr: histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{grpc_type!="server_stream"}[2m])) by (grpc_method,grpc_service, le))

        - record: armada:grpc:server:requestrate
          expr: sum(rate(grpc_server_handled_total[2m])) by (grpc_method,grpc_service)

        - record: armada:log:rate
          expr: sum(rate(log_messages[2m])) by (level)

        - record: armada:resource:available_capacity
          expr: max(armada_cluster_available_capacity) by (pool, cluster, resourceType, nodeType)

        - record: armada:resource:capacity
          expr: max(armada_cluster_capacity) by (pool, cluster, resourceType, nodeType)

        - record: armada:queue:pod_phase:count
          expr: max(armada_queue_leased_pod_count) by (pool, cluster, queueName, phase, nodeType)
{{- end }}
