name: "Docker Readme"
description: "Push Dockerfile README.md to Docker registroy using docker-pushrm Docker plugin"
inputs:
  docker_owner:
    description: "Docker registry owner (i.e. armadaproject, quay.io/armadaproject...)"
    required: true
  docker_provider:
    description: "Docker registry provider (i.e. dockerhub)"
    required: false
    default: "dockerhub"
  docker_user:
    description: "Docker username"
    required: true
  docker_pwd:
    description: "Docker password"
    required: true

runs:
  using: "composite"

  steps:
    - name: Push Armada Bundle README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-bundle
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Bundle'
        readme_file: 'README.md'

    - name: Push Armada Lookout Bundle README
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-lookout-bundle
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Lookout Bundle'
        readme_file: 'README.md'

    - name: Push Armada Full Bundle README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-full-bundle
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Full Bundle'
        readme_file: 'README.md'

    - name: Push Armada Server README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-server
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Server serves as the Control Plane'
        readme_file: 'README.md'

    - name: Push Armada Executor README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-executor
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Executor executes jobs and workflows in a Kubernetes cluster'
        readme_file: 'README.md'

    - name: Push Armada Lookout README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-lookout
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Lookout is responsible for monitoring the state of jobs and workflows'
        readme_file: 'README.md'

    - name: Push Armada Lookout V2 README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-lookoutv2
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Lookout V2 is responsible for monitoring the state of jobs and workflows'
        readme_file: 'README.md'

    - name: Push Armada Lookout Ingester README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-lookoutingester
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Lookout Ingester is responsible for ingesting the state of jobs and workflows'
        readme_file: 'README.md'

    - name: Push Armada Lookout Ingester V2 README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-lookoutingesterv2
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Lookout Ingester V2 is responsible for ingesting the state of jobs and workflows'
        readme_file: 'README.md'

    - name: Push Armada Event Ingester README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-eventingester
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Event Ingester is responsible for ingesting events from Kubernetes'
        readme_file: 'README.md'

    - name: Push Armada Event Ingester V2 README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-eventingesterv2
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Event Ingester V2 is responsible for ingesting events from Kubernetes'
        readme_file: 'README.md'

    - name: Push Armada Scheduler README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-scheduler
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Scheduler is responsible for scheduling jobs and workflows'
        readme_file: 'README.md'

    - name: Push Armada Scheduler Ingester README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-scheduleringester
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Scheduler Ingester is responsible for ingesting the state of jobs and workflows'
        readme_file: 'README.md'

    - name: Push armadactl README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armadactl
        provider: ${{ inputs.docker_provider }}
        short_description: 'armadactl is the command line interface for interacting with Armada Server'
        readme_file: 'README.md'

    - name: Push Job Service README.md
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ inputs.docker_user }}
        DOCKER_PASS: ${{ inputs.docker_pwd }}
      with:
        destination_container_repo: ${{ inputs.docker_owner }}/armada-jobservice
        provider: ${{ inputs.docker_provider }}
        short_description: 'Armada Job Service is responsible for executing jobs and workflows.'
        readme_file: 'README.md'
