name: Build Release Images

on:
  push:
    branches:
      - master

jobs:
  test-and-build-images:
    if: github.repository_owner == 'armadaproject'
    runs-on: ubuntu-22.04
    # runs-on: buildjet-4vcpu-ubuntu-2204
    strategy:
      fail-fast: true
      matrix:
        go: [ '1.20' ]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/workflows/go-setup
      - run: go run github.com/magefile/mage@v1.14.0 -v BuildCI
      - run: go run github.com/magefile/mage@v1.14.0 -v teste2eSetup
      - run: go run github.com/magefile/mage@v1.14.0 -v testse2eNoSetup
        env:
          INTEGRATION_ENABLED: true
      - run: go run github.com/magefile/mage@v1.14.0 -v junitReport
      - name: Upload junit report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: junit.xml
          path: test_reports/junit.xml
          if-no-files-found: error

      - name: Save docker images to artifact
        run: |
          mkdir -p docker-images
          docker save armada-server | gzip > docker-images/armada-server.tar.gz 
          docker save armada-executor | gzip > docker-images/armada-executor.tar.gz
          docker save armadactl | gzip > docker-images/armadactl.tar.gz
          docker save testsuite | gzip > docker-images/testsuite.tar.gz
          docker save armada-lookout | gzip > docker-images/armada-lookout.tar.gz
          docker save armada-lookout-ingester | gzip > docker-images/armada-lookout-ingester.tar.gz
          docker save armada-lookout-v2 | gzip > docker-images/armada-lookout-v2.tar.gz
          docker save armada-lookout-ingester-v2 | gzip > docker-images/armada-lookout-ingester-v2.tar.gz
          docker save armada-event-ingester | gzip > docker-images/armada-event-ingester.tar.gz
          docker save armada-scheduler | gzip > docker-images/armada-scheduler.tar.gz
          docker save armada-scheduler-ingester | gzip > docker-images/armada-scheduler-ingester.tar.gz
          docker save armada-binoculars | gzip > docker-images/armada-binoculars.tar.gz
          docker save armada-jobservice | gzip > docker-images/armada-jobservice.tar.gz

          tar -czf docker-images.tar.gz docker-images/*

      - name: Upload docker image tarball to artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: docker-images
          path: docker-images.tar.gz
          if-no-files-found: error
