name: Python Client

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - 'client/python/**'
      - 'build/python-client/**'
      - 'pkg/api/*.proto'
      - '.github/workflows/python-client.yml'
      - 'docs/python_armada_client.md'
      - 'scripts/build-python-client.sh'
      - '.github/workflows/python-tests/*'

  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'client/python/**'
      - 'build/python-client/**'
      - 'pkg/api/*.proto'
      - '.github/workflows/python-client.yml'
      - 'docs/python_armada_client.md'
      - 'scripts/build-python-client.sh'
      - '.github/workflows/python-tests/*'

jobs:
  python-client-tox:
    strategy:
      matrix:
        go: [ '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No python modified, not running python jobs"'
  python-client-integration-tests:
    strategy:
      matrix:
        go: [ '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No python modified, not running python jobs"'
