name: Deploy GH Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*.md'
      - 'docs/quickstart'
      - 'docs/developer'
      - 'docs/design'
      - '*.md'
      - '.github/workflows/pages.yml'

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: master

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: gh-pages

      - name: Copy site files
        run: |
          cp master/docs/*.md gh-pages/
          rm gh-pages/docs-readme.md
          cp -r master/docs/quickstart gh-pages/
          cp -r master/docs/developer gh-pages/
          cp -r master/docs/design gh-pages/
          cp master/CODE_OF_CONDUCT.md master/CONTRIBUTING.md gh-pages/_pages/

      - name: Commit GH Pages
        run: |
          cd gh-pages
          git config user.name armada-admin
          git config user.email admin@armadaproject.io
          git add . _pages
          git diff --quiet && git diff --staged --quiet || git commit -m "Updating Github Pages branch with latest Master changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
